services:
  chekit-core:
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      SQLITE_PATH: /app/storage/chekit.sqlite
    volumes:
      - chekit-core-data:/app/storage

volumes:
  chekit-core-data:
